# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6959f544493b49557f20e1caf4424a2238087242c06654a8afd06909e86c25150036663abe8dffb66856cce47e797a5ae7cd6726851e418247f17539eae1e44d

test:
  secret_key_base: d24e02b0aa8237bed618d013feda31f02fb2c01984e1633ff69001e8e74228ce34c54c9e39b998141ea997ac058c9c89079f65d4e38ad6c3509f37013abd17d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
